# Generated by Django 5.0.2 on 2025-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_message_options_message_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
